version: '26.2.1'

services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    container_name: postgres
    ports: 
      - '5432:5432'

  app:
    build: .
    command: npm run start:migrate:dev
    ports:
      - "3000:3000"
    container_name: app
    volumes:
      - .:/app
    image: ecommerce-backend